DROP DATABASE IF EXISTS GroupProject;
CREATE DATABASE GroupProject;
USE GroupProject;

CREATE TABLE UserAccount (
	Username VARCHAR(50) NOT NULL PRIMARY KEY,
	Password VARCHAR(50) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL);

CREATE TABLE ToDoList (
	ListID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
    Owner VarCHAR(50) NOT NULL);

CREATE TABLE ToDoListMember (
	MemberID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MemberName VARCHAR(50) NOT NULL,
    ListID INT(11) NOT NULL,
    FOREIGN KEY fk1(ListID) REFERENCES ToDoList(ListID));

CREATE TABLE Task (
	TaskID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TaskInfo VARCHAR(300) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
    ListID INT(11) NOT NULL,
    TaskDeadlineYear INT(4) NOT NULL,
	TaskDeadlineMonth INT(2) NOT NULL,
	TaskDeadlineDay INT(2) NOT NULL,
	TaskDeadlineHour INT(2) NOT NULL,
	TaskDeadlineMinute VARCHAR(2) NOT NULL,
	Completed TINYINT(1) NOT NULL DEFAULT '0',
    FOREIGN KEY fk2(ListID) REFERENCES ToDoList(ListID));

CREATE TABLE Notification (
	NotificationID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Message VARCHAR(300) NOT NULL,
    Owner VARCHAR(50) NOT NULL,
    MarkRead TINYINT(1) NOT NULL DEFAULT 0);

